--- !ditz.rubyforge.org,2008-03-06/project 
name: metaphor
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: metaphor
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: docs
- !ditz.rubyforge.org,2008-03-06/component 
  name: examples
- !ditz.rubyforge.org,2008-03-06/component 
  name: stomp
- !ditz.rubyforge.org,2008-03-06/component 
  name: amqp
- !ditz.rubyforge.org,2008-03-06/component 
  name: websphere
- !ditz.rubyforge.org,2008-03-06/component 
  name: http
- !ditz.rubyforge.org,2008-03-06/component 
  name: stdio
- !ditz.rubyforge.org,2008-03-06/component 
  name: configuration
- !ditz.rubyforge.org,2008-03-06/component 
  name: thread-queue
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: r0.1.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-03-04 03:34:10.755560 Z
    - Sean O'Halpin <sean.ohalpin@gmail.com>
    - created
    - first release
